In [87]:
# Dependencies: pandas and datetime
import pandas as pd
from datetime import datetime

In [88]:
#  Read in CitiBike file path for April 2023
new_file = pd.read_csv('Module 18 Challenge\JC-202304-citibike-tripdata.csv')

In [89]:
# Put csv file into DataFrame
new_file_df = pd.DataFrame(new_file)
new_file_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,59B1078FC3455D5B,electric_bike,2023-04-02 14:50:55,2023-04-02 15:01:24,Hamilton Park,JC009,Hamilton Park,JC009,40.727596,-74.044247,40.727596,-74.044247,member
1,84365D599B6E002E,electric_bike,2023-04-15 21:08:54,2023-04-16 10:54:44,Hamilton Park,JC009,Hamilton Park,JC009,40.727596,-74.044247,40.727596,-74.044247,casual
2,A4F033EAA7810781,classic_bike,2023-04-17 10:35:11,2023-04-17 10:37:53,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member
3,E9051DFD91E516BF,classic_bike,2023-04-07 12:19:31,2023-04-07 12:21:52,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member
4,0F6D86AEC1B29205,classic_bike,2023-04-07 12:28:21,2023-04-07 12:30:23,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80683,DB10C78061D8DE72,electric_bike,2023-04-04 19:58:21,2023-04-04 20:00:41,2 St & Park Ave,HB608,4 St & Grand St,HB301,40.739153,-74.033082,40.742258,-74.035111,casual
80684,540F192D0FEF0DCE,classic_bike,2023-04-14 18:46:17,2023-04-14 19:06:29,Union St,JC051,Monmouth and 6th,JC075,40.718211,-74.083639,40.725685,-74.048790,member
80685,74353C7251042C05,classic_bike,2023-04-04 20:16:23,2023-04-04 20:39:08,Union St,JC051,Marin Light Rail,JC013,40.718211,-74.083639,40.714584,-74.042817,member
80686,F4B95B8815759FEF,electric_bike,2023-04-25 16:34:56,2023-04-25 16:55:22,Union St,JC051,Grove St PATH,JC115,40.718211,-74.083639,40.719410,-74.043090,casual
80687,46E6A207C37D3567,electric_bike,2023-04-09 09:56:42,2023-04-09 10:10:07,Union St,JC051,Grove St PATH,JC115,40.718211,-74.083639,40.719410,-74.043090,casual

In [90]:
# Check data types of data frame
new_file_df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [91]:
# Convert started_at and ended_at columns to datatime data type
new_file_df['started_at'] = pd.to_datetime(new_file_df['started_at'])
new_file_df['ended_at'] = pd.to_datetime(new_file_df['ended_at'])

In [92]:
# Check that started_at and ended_at columns were converted to datetime
new_file_df.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [93]:
# Create a new column for Trip Duration by calculating difference between ended_at and started_at.
# Value given in seconds.
# Form of this code sourced from Saturn Cloud
new_file_df['Trip Duration (seconds)'] = (new_file_df["ended_at"] - new_file_df["started_at"]).dt.seconds
new_file_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Trip Duration (seconds)
0,59B1078FC3455D5B,electric_bike,2023-04-02 14:50:55,2023-04-02 15:01:24,Hamilton Park,JC009,Hamilton Park,JC009,40.727596,-74.044247,40.727596,-74.044247,member,629
1,84365D599B6E002E,electric_bike,2023-04-15 21:08:54,2023-04-16 10:54:44,Hamilton Park,JC009,Hamilton Park,JC009,40.727596,-74.044247,40.727596,-74.044247,casual,49550
2,A4F033EAA7810781,classic_bike,2023-04-17 10:35:11,2023-04-17 10:37:53,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member,162
3,E9051DFD91E516BF,classic_bike,2023-04-07 12:19:31,2023-04-07 12:21:52,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member,141
4,0F6D86AEC1B29205,classic_bike,2023-04-07 12:28:21,2023-04-07 12:30:23,Hamilton Park,JC009,Monmouth and 6th,JC075,40.727596,-74.044247,40.725685,-74.048790,member,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80683,DB10C78061D8DE72,electric_bike,2023-04-04 19:58:21,2023-04-04 20:00:41,2 St & Park Ave,HB608,4 St & Grand St,HB301,40.739153,-74.033082,40.742258,-74.035111,casual,140
80684,540F192D0FEF0DCE,classic_bike,2023-04-14 18:46:17,2023-04-14 19:06:29,Union St,JC051,Monmouth and 6th,JC075,40.718211,-74.083639,40.725685,-74.048790,member,1212
80685,74353C7251042C05,classic_bike,2023-04-04 20:16:23,2023-04-04 20:39:08,Union St,JC051,Marin Light Rail,JC013,40.718211,-74.083639,40.714584,-74.042817,member,1365
80686,F4B95B8815759FEF,electric_bike,2023-04-25 16:34:56,2023-04-25 16:55:22,Union St,JC051,Grove St PATH,JC115,40.718211,-74.083639,40.719410,-74.043090,casual,1226
80687,46E6A207C37D3567,electric_bike,2023-04-09 09:56:42,2023-04-09 10:10:07,Union St,JC051,Grove St PATH,JC115,40.718211,-74.083639,40.719410,-74.043090,casual,805

In [94]:
# Sort the data frame by values in started_at column
new_file_df.sort_values(by = ['started_at'], inplace = True)
new_file_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Trip Duration (seconds)
30898,8519841A9CD3EAD9,electric_bike,2023-04-01 00:00:54,2023-04-01 00:42:17,12 St & Sinatra Dr N,HB201,14 St Ferry - 14 St & Shipyard Ln,HB202,40.750604,-74.024020,40.752961,-74.024353,casual,2483
58395,AEECD9E6B391F964,classic_bike,2023-04-01 00:02:00,2023-04-01 00:12:35,Columbus Park - Clinton St & 9 St,HB501,City Hall - Washington St & 1 St,HB105,40.748285,-74.032490,40.737360,-74.030970,casual,635
77945,C9D8BCB0EC5E8E50,classic_bike,2023-04-01 00:02:43,2023-04-01 00:05:03,6 St & Grand St,HB302,Adams St & 2 St,HB407,40.744398,-74.034501,40.739814,-74.036904,member,140
47560,2BFEFAAD3D0D0256,classic_bike,2023-04-01 00:02:56,2023-04-01 00:34:49,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740847,-74.028523,40.740973,-74.028603,casual,1913
47669,CE305DF6F95127F5,electric_bike,2023-04-01 00:03:01,2023-04-01 00:35:28,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740973,-74.028603,40.740973,-74.028603,casual,1947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45671,65D10BA403FB7DD2,classic_bike,2023-04-30 23:24:28,2023-04-30 23:30:15,Columbus Drive,JC014,Newport PATH,JC066,40.718355,-74.038914,40.727224,-74.033759,member,347
37805,4DFE5CA502F7D2E7,classic_bike,2023-04-30 23:33:40,2023-04-30 23:54:55,Hilltop,JC019,Hilltop,JC019,40.731169,-74.057574,40.731169,-74.057574,member,1275
25719,5D21E8B6F8B17309,classic_bike,2023-04-30 23:37:07,2023-05-01 00:00:25,Riverview Park,JC057,Riverview Park,JC057,40.744716,-74.043790,40.744319,-74.043991,casual,1398
78112,543FCF3F2B08E48A,classic_bike,2023-04-30 23:47:39,2023-04-30 23:50:25,Bloomfield St & 15 St,HB203,11 St & Washington St,HB502,40.754530,-74.026580,40.749985,-74.027150,member,166
12819,7F94A8BC27565C40,electric_bike,2023-04-30 23:48:11,2023-04-30 23:56:34,Baldwin at Montgomery,JC020,Harborside,JC104,40.723659,-74.064194,40.719252,-74.034234,member,503

In [95]:
# Eliminate all rows where Trip Duration is 60 seconds or less.
# Supposedly these had already been taken out to eliminate potential false starts and redocking to ensure that a bike is secure.
# This does not appear to be the case, at least not with this data set.
new_file_df = new_file_df[new_file_df['Trip Duration (seconds)'] > 60]
new_file_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Trip Duration (seconds)
30898,8519841A9CD3EAD9,electric_bike,2023-04-01 00:00:54,2023-04-01 00:42:17,12 St & Sinatra Dr N,HB201,14 St Ferry - 14 St & Shipyard Ln,HB202,40.750604,-74.024020,40.752961,-74.024353,casual,2483
58395,AEECD9E6B391F964,classic_bike,2023-04-01 00:02:00,2023-04-01 00:12:35,Columbus Park - Clinton St & 9 St,HB501,City Hall - Washington St & 1 St,HB105,40.748285,-74.032490,40.737360,-74.030970,casual,635
77945,C9D8BCB0EC5E8E50,classic_bike,2023-04-01 00:02:43,2023-04-01 00:05:03,6 St & Grand St,HB302,Adams St & 2 St,HB407,40.744398,-74.034501,40.739814,-74.036904,member,140
47560,2BFEFAAD3D0D0256,classic_bike,2023-04-01 00:02:56,2023-04-01 00:34:49,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740847,-74.028523,40.740973,-74.028603,casual,1913
47669,CE305DF6F95127F5,electric_bike,2023-04-01 00:03:01,2023-04-01 00:35:28,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740973,-74.028603,40.740973,-74.028603,casual,1947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45671,65D10BA403FB7DD2,classic_bike,2023-04-30 23:24:28,2023-04-30 23:30:15,Columbus Drive,JC014,Newport PATH,JC066,40.718355,-74.038914,40.727224,-74.033759,member,347
37805,4DFE5CA502F7D2E7,classic_bike,2023-04-30 23:33:40,2023-04-30 23:54:55,Hilltop,JC019,Hilltop,JC019,40.731169,-74.057574,40.731169,-74.057574,member,1275
25719,5D21E8B6F8B17309,classic_bike,2023-04-30 23:37:07,2023-05-01 00:00:25,Riverview Park,JC057,Riverview Park,JC057,40.744716,-74.043790,40.744319,-74.043991,casual,1398
78112,543FCF3F2B08E48A,classic_bike,2023-04-30 23:47:39,2023-04-30 23:50:25,Bloomfield St & 15 St,HB203,11 St & Washington St,HB502,40.754530,-74.026580,40.749985,-74.027150,member,166
12819,7F94A8BC27565C40,electric_bike,2023-04-30 23:48:11,2023-04-30 23:56:34,Baldwin at Montgomery,JC020,Harborside,JC104,40.723659,-74.064194,40.719252,-74.034234,member,503

In [96]:
# Drop rows with missing values and reset index
new_file_df.dropna(how = 'any', inplace = True)
new_file_df = new_file_df.reset_index()

C:\Users\Owner\AppData\Local\Temp\ipykernel_5732\1254146365.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_file_df.dropna(how = 'any', inplace = True)

In [97]:
# Popularity of each station as a start and end point calculated
start_popularity = new_file_df["start_station_name"].value_counts()
end_popularity = new_file_df["end_station_name"].value_counts()

# start_popularity and end_popularity converted to data frames
start_popularity = pd.DataFrame(start_popularity)
end_popularity = pd.DataFrame(end_popularity)

# start_popularity and end_popularity data frames merged to new_file_df


new_file_df = new_file_df.merge(start_popularity, how = 'left', on = "start_station_name")
new_file_df = new_file_df.merge(end_popularity, how = 'left', on = "end_station_name")


# Columns that are added on are titled count_x and count_y.
# Rename the columns as Start Station Popularity and End Station Popularity respectively
new_file_df = new_file_df.rename(columns = {"count_x":"Start Station Popularity", "count_y":"End Station Popularity"})

new_file_df

,index,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Trip Duration (seconds),Start Station Popularity,End Station Popularity
0,30898,8519841A9CD3EAD9,electric_bike,2023-04-01 00:00:54,2023-04-01 00:42:17,12 St & Sinatra Dr N,HB201,14 St Ferry - 14 St & Shipyard Ln,HB202,40.750604,-74.024020,40.752961,-74.024353,casual,2483,1169,1529
1,58395,AEECD9E6B391F964,classic_bike,2023-04-01 00:02:00,2023-04-01 00:12:35,Columbus Park - Clinton St & 9 St,HB501,City Hall - Washington St & 1 St,HB105,40.748285,-74.032490,40.737360,-74.030970,casual,635,1199,2004
2,77945,C9D8BCB0EC5E8E50,classic_bike,2023-04-01 00:02:43,2023-04-01 00:05:03,6 St & Grand St,HB302,Adams St & 2 St,HB407,40.744398,-74.034501,40.739814,-74.036904,member,140,690,917
3,47560,2BFEFAAD3D0D0256,classic_bike,2023-04-01 00:02:56,2023-04-01 00:34:49,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740847,-74.028523,40.740973,-74.028603,casual,1913,1460,1448
4,47669,CE305DF6F95127F5,electric_bike,2023-04-01 00:03:01,2023-04-01 00:35:28,Hudson St & 4 St,HB607,Hudson St & 4 St,HB607,40.740973,-74.028603,40.740973,-74.028603,casual,1947,1460,1448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78421,45671,65D10BA403FB7DD2,classic_bike,2023-04-30 23:24:28,2023-04-30 23:30:15,Columbus Drive,JC014,Newport PATH,JC066,40.718355,-74.038914,40.727224,-74.033759,member,347,978,1934
78422,37805,4DFE5CA502F7D2E7,classic_bike,2023-04-30 23:33:40,2023-04-30 23:54:55,Hilltop,JC019,Hilltop,JC019,40.731169,-74.057574,40.731169,-74.057574,member,1275,551,446
78423,25719,5D21E8B6F8B17309,classic_bike,2023-04-30 23:37:07,2023-05-01 00:00:25,Riverview Park,JC057,Riverview Park,JC057,40.744716,-74.043790,40.744319,-74.043991,casual,1398,568,530
78424,78112,543FCF3F2B08E48A,classic_bike,2023-04-30 23:47:39,2023-04-30 23:50:25,Bloomfield St & 15 St,HB203,11 St & Washington St,HB502,40.754530,-74.026580,40.749985,-74.027150,member,166,987,1486
78425,12819,7F94A8BC27565C40,electric_bike,2023-04-30 23:48:11,2023-04-30 23:56:34,Baldwin at Montgomery,JC020,Harborside,JC104,40.723659,-74.064194,40.719252,-74.034234,member,503,693,1191

In [98]:
# Export to csv file.
new_file_df.to_csv('C:\\Users\\Owner\\OneDrive\\Module 18 Challenge\\CitiBikeJC202404.csv')